In [23]:
import pandas as pd
import numpy as np

from collections import Counter

In [ ]:
# De onde que eu peguei isso mesmo?
kaggle_locations = dict({
    "nucleoplasm": 0,
    "nuclear membrane": 1,
    "nucleoli": 2,
    "nucleoli fibrillar center": 3,
    "nuclear speckles": 4,
    "nuclear bodies": 5,
    "endoplasmic reticulum": 6,
    "golgi apparatus": 7,
    "intermediate filaments": 8,
    "actin filaments": 9,
    "focal adhesion sites": 9,
    "microtubules": 10,
    "mitotic spindle": 11,
    "centrosome": 12,
    "centriolar satellite": 12,
    "plasma membrane": 13,
    "cell junctions": 13,
    "mitochondria": 14,
    "aggresome": 15,
    "cytosol": 16,
    "vesicles": 17,
    "peroxisomes": 17,
    "endosomes": 17,
    "lysosomes": 17,
    "lipid droplets": 17,
    "cytoplasmic bodies": 17,
    "no staining": 18
})

In [25]:
df = pd.read_csv("v24_hpa_subcellular_location_expanded.csv")
df = df[['Gene ID', 'Cell Line', 'Location', 'Image']]
df['Image'] = df['Image'].apply(lambda x: x.split('_blue_red_green.jpg')[0])
df['Image'] = df['Image'].apply(lambda x: x.split('/')[-1])

df['Location'] = df['Location'].apply(lambda x: eval(x))
df['Location'] = df['Location'].apply(lambda x: [" ".join(loc.split()[:-1]) for loc in x])
# Colocar "no staining" onde tem []
df['Location'] = df['Location'].apply(lambda x: ["no staining"] if x == [] else x)

print(len(df), "rows of HPA data fetched.")
df.head(10)

83360 rows of HPA data fetched.

,Gene ID,Cell Line,Location,Image
0,ENSG00000000003,CACO-2,"[nucleoli fibrillar center, cytosol]",1832_C1_2
1,ENSG00000000003,CACO-2,"[nucleoli fibrillar center, cytosol]",1832_C1_4
2,ENSG00000000003,RT-4,"[nucleoli fibrillar center, cell junctions, cy...",1843_B2_17_cr5af971a263864
3,ENSG00000000003,RT-4,"[nucleoli fibrillar center, cell junctions, cy...",1843_B2_30_cr5af971a2648d6
4,ENSG00000000003,U2OS,[cytosol],23_H11_1
5,ENSG00000000003,U2OS,[cytosol],23_H11_2
6,ENSG00000000457,OE19,"[golgi apparatus, cytosol]",2038_G11_1
7,ENSG00000000457,OE19,"[golgi apparatus, cytosol]",2038_G11_2
8,ENSG00000000457,SK-MEL-30,[no staining],2142_F7_1
9,ENSG00000000457,SK-MEL-30,[no staining],2142_F7_2

In [26]:
# Mostrar todas as locations
hpav24_locations = set()
for loc in df['Location']:
    hpav24_locations.update(loc)
hpav24_locations

{'acrosome',
 'actin filaments',
 'aggresome',
 'annulus',
 'basal body',
 'calyx',
 'cell junctions',
 'centriolar satellite',
 'centrosome',
 'cleavage furrow',
 'connecting piece',
 'cytokinetic bridge',
 'cytoplasmic bodies',
 'cytosol',
 'end piece',
 'endoplasmic reticulum',
 'endosomes',
 'equatorial segment',
 'flagellar centriole',
 'focal adhesion sites',
 'golgi apparatus',
 'intermediate filaments',
 'kinetochore',
 'lipid droplets',
 'lysosomes',
 'microtubule ends',
 'microtubules',
 'mid piece',
 'midbody',
 'midbody ring',
 'mitochondria',
 'mitotic chromosome',
 'mitotic spindle',
 'no staining',
 'nuclear bodies',
 'nuclear membrane',
 'nuclear speckles',
 'nucleoli',
 'nucleoli fibrillar center',
 'nucleoli rim',
 'nucleoplasm',
 'perinuclear theca',
 'peroxisomes',
 'plasma membrane',
 'primary cilium',
 'primary cilium tip',
 'primary cilium transition zone',
 'principal piece',
 'rods & rings',
 'vesicles'}

In [27]:
dict_locations = set(kaggle_locations.keys())

only_in_df = hpav24_locations - dict_locations
only_in_df

{'acrosome',
 'annulus',
 'basal body',
 'calyx',
 'cleavage furrow',
 'connecting piece',
 'cytokinetic bridge',
 'end piece',
 'equatorial segment',
 'flagellar centriole',
 'kinetochore',
 'microtubule ends',
 'mid piece',
 'midbody',
 'midbody ring',
 'mitotic chromosome',
 'nucleoli rim',
 'perinuclear theca',
 'primary cilium',
 'primary cilium tip',
 'primary cilium transition zone',
 'principal piece',
 'rods & rings'}

In [28]:
only_in_dict = dict_locations - hpav24_locations
only_in_dict

set()

In [29]:
in_both = dict_locations & hpav24_locations
len(in_both), in_both

(27,
 {'actin filaments',
  'aggresome',
  'cell junctions',
  'centriolar satellite',
  'centrosome',
  'cytoplasmic bodies',
  'cytosol',
  'endoplasmic reticulum',
  'endosomes',
  'focal adhesion sites',
  'golgi apparatus',
  'intermediate filaments',
  'lipid droplets',
  'lysosomes',
  'microtubules',
  'mitochondria',
  'mitotic spindle',
  'no staining',
  'nuclear bodies',
  'nuclear membrane',
  'nuclear speckles',
  'nucleoli',
  'nucleoli fibrillar center',
  'nucleoplasm',
  'peroxisomes',
  'plasma membrane',
  'vesicles'})

In [30]:
counter = Counter()

for locs in df['Location']:
    for loc in locs:
        if loc in only_in_df:
            counter[loc] += 1

counter

Counter({'basal body': 1282,
         'primary cilium': 1240,
         'principal piece': 704,
         'mid piece': 650,
         'cytokinetic bridge': 594,
         'nucleoli rim': 552,
         'end piece': 346,
         'primary cilium transition zone': 246,
         'acrosome': 240,
         'flagellar centriole': 206,
         'connecting piece': 174,
         'equatorial segment': 146,
         'mitotic chromosome': 134,
         'primary cilium tip': 132,
         'calyx': 126,
         'perinuclear theca': 122,
         'midbody': 116,
         'annulus': 94,
         'midbody ring': 59,
         'rods & rings': 52,
         'microtubule ends': 34,
         'kinetochore': 10,
         'cleavage furrow': 4})

In [31]:
from collections import Counter

counter = Counter()

for locs in df['Location']:
    for loc in locs:
        if loc in in_both:
            counter[loc] += 1

counter

Counter({'nucleoplasm': 30988,
         'cytosol': 24292,
         'vesicles': 9974,
         'no staining': 9315,
         'plasma membrane': 9239,
         'mitochondria': 5362,
         'golgi apparatus': 5138,
         'nucleoli': 4444,
         'nuclear speckles': 2555,
         'endoplasmic reticulum': 2513,
         'nuclear bodies': 2496,
         'microtubules': 1860,
         'centrosome': 1857,
         'nucleoli fibrillar center': 1527,
         'nuclear membrane': 1348,
         'actin filaments': 1018,
         'cell junctions': 1000,
         'centriolar satellite': 810,
         'intermediate filaments': 546,
         'focal adhesion sites': 545,
         'cytoplasmic bodies': 316,
         'mitotic spindle': 304,
         'lipid droplets': 130,
         'aggresome': 124,
         'peroxisomes': 104,
         'lysosomes': 66,
         'endosomes': 54})

In [32]:
df

,Gene ID,Cell Line,Location,Image
0,ENSG00000000003,CACO-2,"[nucleoli fibrillar center, cytosol]",1832_C1_2
1,ENSG00000000003,CACO-2,"[nucleoli fibrillar center, cytosol]",1832_C1_4
2,ENSG00000000003,RT-4,"[nucleoli fibrillar center, cell junctions, cy...",1843_B2_17_cr5af971a263864
3,ENSG00000000003,RT-4,"[nucleoli fibrillar center, cell junctions, cy...",1843_B2_30_cr5af971a2648d6
4,ENSG00000000003,U2OS,[cytosol],23_H11_1
...,...,...,...,...
83355,ENSG00000291316,HeLa,[no staining],1282_B2_4
83356,ENSG00000291316,PC-3,[nucleoplasm],1218_C5_1
83357,ENSG00000291316,PC-3,[nucleoplasm],1218_C5_3
83358,ENSG00000291316,U2OS,[no staining],1018_C5_1
83359,ENSG00000291316,U2OS,[no staining],1018_C5_2

In [33]:
# Keep only rows where all locations are in in_both
df_filtered = df[df['Location'].apply(lambda labels: set(labels).issubset(in_both))]
len(df_filtered)

78453

In [34]:
# Pegar todos os nomes de arquivos dentro de uma pasta ../hpa-datasets/v24/images/cell_crops
import os

# Pasta com os cell crops
cell_crops_dir = "../hpa-datasets/v24/images/cell_crops"

# Listar arquivos
files = [
    f for f in os.listdir(cell_crops_dir)
    if f.endswith(".png")
]

# Extrair ID da imagem (tudo antes do último "_")
image_ids = [
    "_".join(f.split("_")[:-1]) for f in files
]

# Contar número de células por imagem
cell_counts = Counter(image_ids)

In [35]:
len(cell_counts)

45012

In [36]:
# Verificar se todos os ids de cell_counts (Counter) estão em df_filtered
ids_cell_counts = set(cell_counts.keys())
ids_df = set(df_filtered["Image"])

missing_ids = ids_cell_counts - ids_df
len(missing_ids), list(missing_ids)[:10]

(1182,
 ['1027_F12_7',
  '575_B2_1',
  '1050_F1_3',
  '1888_E1_5',
  '1169_D3_4',
  '1150_B8_9',
  '627_F1_1',
  '1952_A2_5',
  '1909_C4_4',
  '264_A12_2'])

In [37]:
locs = df_filtered[df_filtered['Image']=='1027_F12_7']['Location']
len(locs)

0

In [38]:
NUM_CLASSES = 19

rows = []

for image_id, n_cells in cell_counts.items():
    # Pega as localizações dessa imagem
    locs = df_filtered[df_filtered['Image']==image_id]['Location']

    if len(locs) > 0:
        row = {
            "ID": image_id,
            "fold": -1,
            "idx": n_cells
        }
        # Inicializa todas as classes com 0
        for i in range(NUM_CLASSES):
            row[f"class{i}"] = 0
        
        locs = locs.iloc[0]  # lista de strings

        for loc in locs:
            if loc in kaggle_locations:
                cls_idx = kaggle_locations[loc]
                row[f"class{cls_idx}"] = 1
            else:
                # opcional: logar classes fora do mapeamento
                pass

        rows.append(row)

df_out = pd.DataFrame(rows)

In [39]:
ordered_cols = (
    ["ID"]
    + [f"class{i}" for i in range(NUM_CLASSES)]
    + ["fold", "idx"]
)

df_out = df_out[ordered_cols]

df_out

,ID,class0,class1,class2,class3,class4,class5,class6,class7,class8,...,class11,class12,class13,class14,class15,class16,class17,class18,fold,idx
0,1610_F3_2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,-1,33
1,884_G12_4,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,-1,14
2,509_C1_3,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,-1,25
3,107_F12_1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,-1,15
4,429_E7_3,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,-1,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43825,1790_B8_2,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,-1,5
43826,1235_C6_1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,-1,4
43827,1790_C5_4,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,-1,5
43828,1658_F5_2,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,-1,1
43829,991_B8_1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,-1,4

In [40]:
df_out.to_csv("kaggle_labels_hpa_v24.csv", index=False)

In [41]:
len(cell_counts) - len(missing_ids)

43830